version: "3.7"

networks:
  llmagent-network:
    driver: bridge

volumes:
  postgres:
  chromadb:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llmagent-backend
    ports:
      - "${BACKEND_PORT:-9000}:9000"
    volumes:
      - ./:/code
    depends_on:
      - postgres
      - chroma
    networks:
      - llmagent-network
    
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    networks:
      - llmagent-network
    restart: unless-stopped

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - "${CHROMA_PORT:-8000}:${CHROMA_PORT:-8000}"
    volumes:
      - chromadb:/chroma/chroma/
    networks:
      - llmagent-network
    restart: unless-stopped
